// Isolated UI verification only. No credentials, real AI, network sources, or notes.
export {};
const build = await Bun.build({ entrypoints: ['tests/browser-preview.ts'], target: 'browser', format: 'esm' });
if (!build.success) throw new Error(build.logs.join('\n'));
const script = await build.outputs[0].text();
const server = Bun.serve({ hostname: '127.0.0.1', port: 4179, fetch(request) {
  if (new URL(request.url).pathname === '/preview.js') return new Response(script, { headers: { 'Content-Type': 'text/javascript' } });
  return new Response(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>热点追踪 · 模拟宿主验证</title><style>:root{color-scheme:light;--ink:#14251c;--muted:#66756c;--line:#dce5df;--surface:#fff;--soft:#f4f7f5;--green:#16a06e}*{box-sizing:border-box}body{margin:0;background:#edf2ef;color:var(--ink);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}.preview-bar{padding:14px 24px;background:var(--surface);border-bottom:1px solid var(--line);box-shadow:0 1px 3px rgba(15,31,23,.04)}.preview-notice{display:flex;align-items:center;gap:8px;margin:0 0 12px;color:#745d2b;font-size:12px}.preview-notice:before{content:"模拟";padding:2px 7px;border-radius:999px;background:#fff1c7;color:#765817;font-size:11px;font-weight:700}form{display:flex;align-items:flex-end;gap:10px;flex-wrap:wrap}label{display:grid;gap:5px;color:var(--muted);font-size:12px;font-weight:600}input,select,button{min-height:36px;border:1px solid #cfd9d3;border-radius:7px;background:var(--surface);color:var(--ink);font:inherit}input,select{padding:7px 10px}input{width:min(320px,72vw)}select{min-width:104px}button{padding:7px 13px;cursor:pointer;font-weight:600}button:hover{background:var(--soft);border-color:#b9c8bf}button[type=submit]{border-color:var(--green);background:var(--green);color:#fff}button[type=submit]:hover{filter:brightness(.96)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid color-mix(in srgb,var(--green) 35%,transparent);outline-offset:2px}.preview-actions{display:flex;gap:8px;margin-left:auto}#status{min-height:20px;margin:10px 0 0;color:var(--muted);font-size:12px}iframe{display:block;width:100%;height:calc(100vh - 132px);margin:auto;border:0;background:#fff}@media(max-width:720px){.preview-bar{padding:12px 14px}.preview-actions{width:100%;margin-left:0}iframe{height:calc(100vh - 220px)}}</style><div class="preview-bar"><p class="preview-notice">来源、AI、笔记和调度均为测试替身，不调用外部服务。</p><form id="settings"></form><div id="status" role="status">尚未保存模拟笔记</div></div><iframe id="panel" title="热点追踪面板"></iframe><script type="module" src="/preview.js"></script></html>`, { headers: { 'Content-Type': 'text/html;charset=utf-8', 'Cache-Control': 'no-store' } });
} });
console.log(`Synthetic UI preview: http://127.0.0.1:${server.port}`);
